name: SonarCloud Analysis

on:
  pull_request:
    branches:
      - develop
      - feature/lab4

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests and coverage
        run: |
          pytest --cov=app --cov-report=xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/17.0.12-7/x64
          PATH: /opt/hostedtoolcache/Java_Adopt_jdk/17.0.12-7/x64/bin:$PATH
        with:
          args: >
            -Dsonar.organization=bhos-qa
            -Dsonar.projectKey=bhos-qa_lab-4-aykhanmv
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=app
            -Dsonar.tests=app
            -Dsonar.python.interpreter=python
            -X